Fixes fatal error: invalid pointer found on stack
If we use unsafe.Pointer for the windows.Handle for hcceLocalMachine, we
sometimes get a panic when resolveChains is called often in an application:

```runtime: bad pointer in frame github.com/google/certtostore.(*WinCertStore).resolveChains at 0xc000041c60: 0x1
fatal error: invalid pointer found on stack```

vsCode also says that this is a possible misuse of unsafe.Pointer.